name: 🔔 Notify Parent Repo to Deploy

on:
  push:
    branches:
      - main-release   # La branche utilisée par ce submodule (voir .gitmodules)

jobs:
  notify-parent:
    name: Trigger Deployment in Parent Repo
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout submodule
        uses: actions/checkout@v4

      - name: 🔄 Update submodule reference in parent repo and trigger deploy
        run:
            echo "test"
          fi
